FEDERATION_SERVER = "$FEDERATION_URL"
AUTH_SERVER = "$COMPLIANCE_URL"
SIGNING_KEY = "$RECEIVING_ACCOUNT"

[[CURRENCIES]]
code = "$CURRENCY_CODE"
conditions = "$CONDITIONS"
desc = "$DESC"
display_decimals = $DECIMALS
image = "$IMAGE_URL"
issuer = "$ISSUER"
name = "$CURRENCY"
